version: '3.8'

# Development-specific Docker Compose configuration
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  # Development app with hot reload
  app:
    build:
      target: build  # Use the build stage for development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
      - "24678:24678"  # HMR port

  # Prisma Studio for database management
  prisma-studio:
    profiles: []  # Always include in dev mode

  # Database admin interface (phpMyAdmin)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pammboo2-phpmyadmin
    environment:
      - PMA_HOST=database
      - PMA_USER=${MYSQL_USER:-pammboo_user}
      - PMA_PASSWORD=${MYSQL_PASSWORD:-pammboo_password}
    ports:
      - "${PHPMYADMIN_PORT:-8080}:80"
    depends_on:
      - database
    networks:
      - consent-network