name: Delete Docker Image on Release Deletion

on:
  release:
    types: [deleted]

permissions:
  contents: read
  packages: write
  actions: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{ github.event.release.tag_name }}

jobs:
  delete-image:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete Docker image
        run: |
          gh auth login --with-token <<< ${{ secrets.GITHUB_TOKEN }}
          gh api -X DELETE \
            "/repos/${{ github.repository }}/packages/container/${{ env.IMAGE_NAME }}/versions/${{ env.IMAGE_TAG }}"
          echo "Deleted image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"